include mocha.conf
#include macchiato.conf
#include tokyo-night.conf
#include ayu.conf

font_family      FiraCode Nerd Font
font_size        15

background_opacity 0.8

remember_window_size   no
initial_window_width   900
initial_window_height  600

active_tab_font_style   bold
inactive_tab_font_style normal

map ctrl+shift+t new_tab
map ctrl+shift+n new_window
map ctrl+shift+plus change_font_size all +2.0
map ctrl+shift+minus change_font_size all -2.0
map ctrl+shift+backspace change_font_size all 0

mouse_hide_wait 1.0
copy_on_select yes
cursor_trail 1

confirm_os_window_close 0

shell zsh
