general {
    intensity = 2
    size_min = 1.0
    size_max = 3.0
    speed_min = 30.0
    speed_max = 80.0
    drift = 20.0
    max_opacity = 1.0
    #image_path = "/path/to/snowflake/image.png"
    #image_path = "/path/to/snowflake/image2.png"
}
